language: csharp
install:
  - nuget restore BowlingSPAService/BowlingSPAService.sln
  - nuget restore BowlingSPAWeb/BowlingSPA.sln
script : 
  - msbuild /p:Configuration=Release BowlingSPAService/BowlingSPAService.sln
  - msbuild /p:Configuration=Release BowlingSPAWeb/BowlingSPA.sln